apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: elasticsearch
    version: v7.10.2
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v7.10.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v7.10.2
    spec:
     containers:
     - image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
       name: elasticsearch
       env:
        - name: discovery.type
          value: single-node
       readinessProbe:
         tcpSocket:
           port: 9200
         initialDelaySeconds: 5
         timeoutSeconds: 10
       resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    k8s-app: elasticsearch
    version: v7.10.2
  type: ClusterIP
status:
  loadBalancer: {}
