apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: kibana
    version: v7.12.0
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
      version: v7.12.0
  template:
    metadata:
      labels:
        k8s-app: kibana
        version: v7.12.0
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.12.0
          readinessProbe:
            httpGet:
               path: /
               port: 5601
            initialDelaySeconds: 5
            timeoutSeconds: 10
          env:
           - name: ELASTICSEARCH_HOSTS
             value: http://elasticsearch:9200
           - name: SERVER_NAME
             value: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    k8s-app: kibana
    version: v7.12.0
  type: NodePort
status:
  loadBalancer: {}